spring:
  jmx:
    enabled: false
  datasource:
    url: jdbc:sqlite:./data/bee_data.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  type-aliases-package: com.app.po
  mapper-locations: classpath:mapper/*.xml
  #  springboot 2.7 使用swagger3时需要配置此项
spring.mvc.pathmatch.matching-strategy: ant_path_matcher