spring:
  main:
    allow-circular-references: true
  jmx:
    enabled: false
  datasource:
    url: jdbc:sqlite:./data/bee_data.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  type-aliases-package: com.app.po
  mapper-locations: classpath:mapper/*.xml
#  springboot 2.7 使用swagger3时需要配置此项
spring.mvc.pathmatch.matching-strategy: ant_path_matcher
jwt:
  #JWT存储的请求头
  tokenHeader: Authorization
  #JWT加解密使用的秘钥
  secret: yeb-secret
  #JWT超期限时间
  expiration: 604800
  #JWT 负载中拿到的开头
  tokenHead: Bearer

logging:
  config: classpath:logger/loggerConfig.xml